In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_diamonds'
response = requests.get(url)
soup = BeautifulSoup(response.content)
soup_table = soup.find('table', class_='wikitable')
soup_rolls = soup_table.find_all('tr')
names = []
uncut_weights = []
cut_weights = []
colors = []
countries = []

for roll in soup_rolls[1:]:
    soup_spoons = roll.find_all('td')
    name = soup_spoons[0].get_text()
    names.append(name)

    uncut_weight = soup_spoons[1].get_text()
    uncut_weights.append(uncut_weight)

    cut_weight = soup_spoons[2].get_text()
    cut_weights.append(cut_weight)

    color = soup_spoons[3].get_text()
    colors.append(color)


len(names), len(uncut_weights)

diamond_df = pd.DataFrame({'name':names,'uncut_weights':uncut_weights})

NameError: name 'requests' is not defined

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL de la page Wikipedia
url = "https://en.wikipedia.org/wiki/List_of_diamonds#List_of_diamonds"

# Faire la requête HTTP
response = requests.get(url)

# Vérifier si la requête a réussi
if response.status_code == 200:
    # Parser le contenu HTML
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Trouver le tableau sur la page
    table = soup.find('table', {'class': 'wikitable'})

    # Extraire les données du tableau
    rows = table.find_all('tr')
    
    # Créer une liste pour stocker les données
    data = []

    # Parcourir les lignes du tableau
    for row in rows:
        # Trouver toutes les cellules dans la ligne
        cells = row.find_all(['th', 'td'])
        # Extraire le texte de chaque cellule
        row_data = [cell.get_text(strip=True) for cell in cells]
        # Ignorer la ligne si elle est vide
        if row_data:
            # Ignorer la colonne d'image
            if row_data[0] != "Image":
                data.append(row_data)

    # Convertir les données en DataFrame en utilisant pandas
    df_countryorigin= pd.DataFrame(data[1:], columns=data[0])

df_countryorigin

,Name,Uncutweight(carat),Cutweight(carat),Color,Country/region of origin,Description,Image
0,26th Congress of the Communist Party of the So...,342.57,,yellow,Russia / USSR,"Mined at theMir kimberlitic pipe(Yakutia,Russi...",—
1,4 February Stone (The Art of de GRISOGONO)[8],404.2,163.41[9],white,Angola,27th largest white diamond found (at that time...,—
2,Akbar Shah,116,71.7,colorless,India,An Indian diamond which became famous during t...,—
3,Alexander Pushkin[6][7],320.65,,colorless,Russia / USSR,Mined at theUdachnaya kimberlitic pipe(Yakutia...,—
4,Allnatt Diamond,,101.29,yellow,South Africa (disputed),A 101.29-carat (20.258 g) antique cushion-shap...,Allnatt
...,...,...,...,...,...,...,...
113,Vargas diamond,726.6,,blue-white,Brazil,Cut into 29 smaller diamonds.,—
114,Williamson pink diamond,54.5,23.6,pink,Tanzania,Given toQueen Elizabeth IIon her wedding in 19...,—
115,Williamson Pink Star,32.32,11.15,pink,Tanzania,The cushion-shaped flawless fancy vivid pinkty...,—
116,Winston Pink Legacy,,18.96,pink,South Africa,The world's largest Fancy Vivid Pink. Previous...,—
117,Wittelsbach-Graff Diamond,35.56,31.06,blue,India,"31.06 carats (6.212 g), Fancy Deep Blue, cushi...","Wittelsbach diamond, before being recut by Graff"

In [3]:
df_countryorigin = df_countryorigin.drop(columns=['Image'])
df_countryorigin

,Name,Uncutweight(carat),Cutweight(carat),Color,Country/region of origin,Description
0,26th Congress of the Communist Party of the So...,342.57,,yellow,Russia / USSR,"Mined at theMir kimberlitic pipe(Yakutia,Russi..."
1,4 February Stone (The Art of de GRISOGONO)[8],404.2,163.41[9],white,Angola,27th largest white diamond found (at that time...
2,Akbar Shah,116,71.7,colorless,India,An Indian diamond which became famous during t...
3,Alexander Pushkin[6][7],320.65,,colorless,Russia / USSR,Mined at theUdachnaya kimberlitic pipe(Yakutia...
4,Allnatt Diamond,,101.29,yellow,South Africa (disputed),A 101.29-carat (20.258 g) antique cushion-shap...
...,...,...,...,...,...,...
113,Vargas diamond,726.6,,blue-white,Brazil,Cut into 29 smaller diamonds.
114,Williamson pink diamond,54.5,23.6,pink,Tanzania,Given toQueen Elizabeth IIon her wedding in 19...
115,Williamson Pink Star,32.32,11.15,pink,Tanzania,The cushion-shaped flawless fancy vivid pinkty...
116,Winston Pink Legacy,,18.96,pink,South Africa,The world's largest Fancy Vivid Pink. Previous...
117,Wittelsbach-Graff Diamond,35.56,31.06,blue,India,"31.06 carats (6.212 g), Fancy Deep Blue, cushi..."

In [4]:
def clean_references(x):
    return re.sub("\[[0-9]+\]","", x).strip()

#df_countryorigin["Name"] = df_countryorigin["Name"].a
df_countryorigin = df_countryorigin.applymap(clean_references)

NameError: name 're' is not defined

In [ ]:
df_countryorigin.replace('', 'Unknown', inplace=True)

In [5]:
df_countryorigin.to_csv('df_countryorigin.csv')

In [6]:
df_countryorigin['Country/region of origin'] = df_countryorigin['Country/region of origin'].replace('-', 'Unknown')

In [7]:
df_countryorigin

,Name,Uncutweight(carat),Cutweight(carat),Color,Country/region of origin,Description
0,26th Congress of the Communist Party of the So...,342.57,,yellow,Russia / USSR,"Mined at theMir kimberlitic pipe(Yakutia,Russi..."
1,4 February Stone (The Art of de GRISOGONO)[8],404.2,163.41[9],white,Angola,27th largest white diamond found (at that time...
2,Akbar Shah,116,71.7,colorless,India,An Indian diamond which became famous during t...
3,Alexander Pushkin[6][7],320.65,,colorless,Russia / USSR,Mined at theUdachnaya kimberlitic pipe(Yakutia...
4,Allnatt Diamond,,101.29,yellow,South Africa (disputed),A 101.29-carat (20.258 g) antique cushion-shap...
...,...,...,...,...,...,...
113,Vargas diamond,726.6,,blue-white,Brazil,Cut into 29 smaller diamonds.
114,Williamson pink diamond,54.5,23.6,pink,Tanzania,Given toQueen Elizabeth IIon her wedding in 19...
115,Williamson Pink Star,32.32,11.15,pink,Tanzania,The cushion-shaped flawless fancy vivid pinkty...
116,Winston Pink Legacy,,18.96,pink,South Africa,The world's largest Fancy Vivid Pink. Previous...
117,Wittelsbach-Graff Diamond,35.56,31.06,blue,India,"31.06 carats (6.212 g), Fancy Deep Blue, cushi..."

In [8]:
df_countryorigin.to_csv('df_countryorigin.csv')